Initialize firebase and added firebase.js config file
TeamPetPoison/pet-poison-alert pull request #10
Opened 2023-03-16 20:07 UTC by ranegray

This should be everything we need to start coding. Everything else can be handled in the firebase console which I will add people too.

2023-03-16 20:08 UTC, ranegray commented
This is my first ever PR so lemme know if I'm dumb or did something wrong.

2023-03-16 21:21 UTC, MacAndersonUche commented on firebaseConfig.js
> +const db = getFirestore(app);
Can these be named properly, please?

2023-03-16 21:21 UTC, MacAndersonUche commented on firebaseConfig.js
> +  apiKey: process.env.apiKey,
Nice, well done man :)

2023-03-16 21:22 UTC, MacAndersonUche commented on firebaseConfig.js
> +  storageBucket: "pet-poison-alert.appspot.com",
Worth adding this to the env as well please

2023-03-16 21:23 UTC, ranegray commented on firebaseConfig.js
> +const db = getFirestore(app);
These are named per the docs. You want em named database and firebaseAnalytics?

2023-03-16 21:25 UTC, MacAndersonUche commented on firebaseConfig.js
> +const db = getFirestore(app);
something a bit more descriptive please would do :)

2023-03-16 22:10 UTC, MacAndersonUche commented
Nice Looks Good to me

2023-03-16 22:12 UTC, MacAndersonUche submitted a review, later dismissed

2023-03-18 03:05 UTC, MacAndersonUche commented
@toreylittlefield  please review this

2023-03-19 14:35 UTC, toreylittlefield commented
@MacAndersonUche / @ranegray  you want to fix this up so we can merge it?

2023-03-19 14:41 UTC, ranegray commented
@toreylittlefield do i just delete the conflict markers using the web editor?

2023-03-19 14:47 UTC, toreylittlefield commented
@ranegray first switch to main. 

Then pull down the changes `git pull`

Then switch back to your branch here.

Then merge main onto your branch `git merge origin/main`

You'll have the chance to solve the merge conflicts. I recommend just solving the conflicts in the package.json. Looks like new files have been installed. Don't worry about the package-lock it'll be too big a pain in the ass.

once you resolve the merge conflicts in package.json. Just delete package-lock and then run `npm install` it'll create a new package lock. Push up all the new changes for the package.json and package-lock 👍

2023-03-19 14:50 UTC, toreylittlefield requested changes

2023-03-19 15:08 UTC, ranegray commented on firebaseConfig.js
> +  measurementId: process.env.measurementId
From the docs (https://firebase.google.com/docs/projects/api-keys):

> Unlike how API keys are typically used, API keys for Firebase services are not used to control access to backend resources; that can only be done with Firebase Security Rules (to control which users can access resources) and App Check (to control which apps can access resources).
> 
> Usually, you need to fastidiously guard API keys (for example, by using a vault service or setting the keys as environment variables); however, API keys for Firebase services are ok to include in code or checked-in config files.

2023-03-19 15:11 UTC, toreylittlefield commented on firebaseConfig.js
> +  measurementId: process.env.measurementId
@ranegray you're right but maybe safer for now to use the `.env.local` because we haven't set the Firebase Security Rules

2023-03-19 15:15 UTC, ranegray commented on firebaseConfig.js
> +  measurementId: process.env.measurementId
There is a `.env.local` i created it. do you want me to put that file somewhere. obviously its not going to push to GitHub

2023-03-19 15:21 UTC, toreylittlefield commented on firebaseConfig.js
> +  measurementId: process.env.measurementId
@ranegray yep you're right no need to share it 😄 Just please update the variable name for those secrets to use the NEXT_PUBLIC syntax thank you!

2023-03-20 04:01 UTC, toreylittlefield approved these changes

2023-03-20 04:05 UTC, toreylittlefield commented
@ranegray nice work and thanks! I got it working on my end using my own firebase credentials 💯 . 

I'll merge for now but my suggestion is to move out this file into the `lib` directory under a `firebase` dir. So `lib/firebase/firebaseConfig.js` or something.

Another thing is the `env` variable names should be all uppercase and separated with an underscore. This is just JS convention. It doesn't change anything.

`NEXT_PUBLIC_apiKey -> NEXT_PUBLIC_API_KEY`

Last thing 
`const firebaseAnalytics = getAnalytics(app);` throws an a `window not defined error`. It's a nextjs thing because of SSR. I think we don't need the analytics right now so we can remove it and figure out the solution later.

I'll create a separate ticket for these issues. Again great job and congrats!

2023-03-20 04:09 UTC, merged