zoom control setup
TeamPetPoison/pet-poison-alert pull request #27
Opened 2023-03-22 05:08 UTC by Netdreion

This is a React component that renders a map using the Leaflet library, with a marker pointing to a specified location and zoom controls.

2023-03-23 06:23 UTC, toreylittlefield requested changes
@Netdreion please see my branch https://github.com/TeamPetPoison/pet-poison-alert/pull/30

2023-03-24 00:27 UTC, Netdreion commented on lib/Components/Map.jsx
> +function Map() {
ok , it done

2023-03-24 00:37 UTC, Netdreion commented on lib/Components/Map.jsx
> +  const center = L.latLng(geoData.lat, geoData.lng);
you are right we dont need this since we have the marker.

2023-03-24 00:38 UTC, Netdreion commented on lib/Components/Map.jsx
> +  const locationIconUrl = encodeURI(
ok , will be fixed

2023-03-24 00:38 UTC, Netdreion commented on lib/Components/Map.jsx
> +      <Marker position={center} icon={locationIconSvg} />
ok will be updated

2023-03-25 03:24 UTC, Netdreion commented
Updated with suggestions, removed unnecessary code .

2023-03-25 11:39 UTC, toreylittlefield commented
@Netdreion looks like there are a few merge conflicts because I merge a branch. If you need help resolving them let me know.

2023-03-25 11:41 UTC, toreylittlefield commented on package.json
> +    "react-icons": "^4.8.0",
Remove this package

2023-03-25 11:41 UTC, toreylittlefield commented on package.json
> +    "heroicons": "^2.0.16",
remove this package too

2023-03-25 11:41 UTC, toreylittlefield commented on package.json
> +    "@heroicons/react": "^1.0.6",
wrong version, use the latest

2023-03-25 11:42 UTC, toreylittlefield commented on styles/globals.css
> +}
is there an `<svg />`? Did you see my branch? Is this matching the spec from the figma file?

2023-03-25 11:42 UTC, toreylittlefield commented on lib/Components/Map.jsx
> +      <button onClick={handleButtonClick}>Update GeoData</button>
we don't need a button yet

2023-03-25 11:43 UTC, toreylittlefield commented on lib/Components/Map.jsx
> +        center={[geoData.lat, geoData.lng]}
that works or you can just pass in `geoData` since it's an object with the right properties

2023-03-25 11:44 UTC, toreylittlefield commented on styles/globals.css
> +}
@Netdreion can we go over the changes together sometime please?

2023-03-30 05:52 UTC, toreylittlefield commented
![image](https://user-images.githubusercontent.com/52614742/228742006-e0d9f5a3-1cf5-4564-ac37-44c25474c24e.png)
 Bravo @Netdreion thanks! 🚀

2023-03-30 05:52 UTC, merged