WIP rg/32 report incident form
TeamPetPoison/pet-poison-alert pull request #35
Opened 2023-03-31 11:39 UTC by ranegray

Built out multipage form from issue #32. Added Zustand FormStore and multiple view components and navigation components. Data is persisting globally right now and being stored in Zustand formStore.js.

I've commented out Map and NavBar while working on this component.

2023-04-30 11:12 UTC, Netdreion commented
Nicely done

2023-04-30 11:13 UTC, Netdreion submitted a review, later dismissed
nicely done !

2023-05-02 04:13 UTC, toreylittlefield commented on packages/client/lib/components/BottomNav/BottomNav.jsx
> +  const { setShowForm } = useFormStore()
don't destructure here as discussed with the zustand store best practices: https://docs.pmnd.rs/zustand/getting-started/introduction#then-bind-your-components,-and-that's-it!

2023-05-02 04:14 UTC, toreylittlefield commented on packages/client/lib/components/BottomNav/BottomNav.jsx
>        <div></div>
nit: wondering if we can remove the empty `div` here 😆

2023-05-02 04:16 UTC, toreylittlefield commented on packages/client/lib/components/BottomNav/BottomNav.jsx
> +      <div onClick={() => setShowForm(true)}  className="rounded-full fixed bottom-0 h-24 w-24 flex items-center justify-center bg-white">
```suggestion
      <div onClick={() => setShowForm(true)}  className="rounded-full fixed bottom-0 h-24 w-24 flex items-center justify-center bg-background">
```

2023-05-02 04:47 UTC, toreylittlefield commented on packages/client/lib/components/BottomNav/BottomNav.jsx
>        <div></div>
Update @ranegray 

what do you think of this to remove the empty `<div />`? 

```JS
<div onClick={() => setShowForm(true)} className="relative">
  <div className="absolute left-0 bottom-0 translate-y-1/3 rounded-full h-24 w-24 flex items-center justify-bg-background">
    <div className="rounded-full h-20 w-20 flex items-center justify-center bg-primary ">
      <button className="rounded-full h-16 w-16 flex items-center justify-center bg-backgroundAlt">
        <PlusCircleIcon className="h-6 w-6 text-primary" />
      </button>
    </div>
  </div>
</div>
```

I used the `position: relative;` prop on the parent `<div />` and then used a `translate-y-1/3` to hopefully get the "circle" button in the spot where you had it.

2023-05-02 04:50 UTC, toreylittlefield commented on packages/client/lib/components/BottomNav/BottomNav.jsx
>  const BottomNav = () => {
Outside the scope of this PR but what do you think of this refactor of the `BottomNav.jsx` component to help "DRY" up the component?

```JS
import { useState } from 'react';
import BottomNavItem from './BottomNavItem.jsx';
import {
  HomeIcon,
  MagnifyingGlassIcon,
  UserIcon,
  PlusCircleIcon,
  MapPinIcon,
} from '@heroicons/react/24/outline';
import useFormStore from '@/store/formStore.js';

const BOTTOM_NAV_ITEMS = [
  {
    name: 'Home',
    icon: <HomeIcon className="h-6 w-6 pointer-events-none" />,
  },
  {
    name: 'Search',
    icon: <MagnifyingGlassIcon className="h-6 w-6 pointer-events-none" />,
  },
  {
    name: 'Layers',
    icon: <MapPinIcon className="h-6 w-6 pointer-events-none" />,
  },
  {
    name: 'Profile',
    icon: <UserIcon className="h-6 w-6 pointer-events-none" />,
  },
];

const LEFT_NAV_ITEMS = BOTTOM_NAV_ITEMS.slice(0, 2);
const RIGHT_NAV_ITEMS = BOTTOM_NAV_ITEMS.slice(2, 4);

const BottomNav = () => {
  const [active, setActive] = useState('');
  const { setShowForm } = useFormStore();

  const handleActive = (name) => {
    setActive(name);
  };

  const isActive = (name) => {
    return active === name ? true : false;
  };

  return (
    <div className="absolute bottom-0 z-[9999] w-full h-16 text-foreground/30 rounded-t-2xl p-1 grid grid-cols-5 justify-items-center items-center bg-white">
      {LEFT_NAV_ITEMS.map((item) => (
        <BottomNavItem
          key={item.name}
          setActive={() => handleActive(item.name)}
          selected={isActive(item.name)}
          name={item.name}
        >
          {item.icon}
        </BottomNavItem>
      ))}
      <div onClick={() => setShowForm(true)} className="relative">
        <div className="absolute left-0 bottom-0 translate-y-1/3 rounded-full h-24 w-24 flex items-center justify-center bg-background">
          <div className="rounded-full h-20 w-20 flex items-center justify-center bg-primary ">
            <button className="rounded-full h-16 w-16 flex items-center justify-center bg-backgroundAlt">
              <PlusCircleIcon className="h-6 w-6 text-primary" />
            </button>
          </div>
        </div>
      </div>
      {RIGHT_NAV_ITEMS.map((item) => (
        <BottomNavItem
          key={item.name}
          setActive={() => handleActive(item.name)}
          selected={isActive(item.name)}
          name={item.name}
        >
          {item.icon}
        </BottomNavItem>
      ))}
    </div>
  );
};

export default BottomNav;
```

2023-05-02 04:59 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> +        if (!map) return;
is this `!map` conditional required?

2023-05-02 05:09 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> +    };
this is great. Nice fix for the bug on the `map.setView` if the geolocation is not yet set. Maybe instead of a new `useEffect` we could use the one above and refactor to something like this?

```JS
    useEffect(() => {
    // TODO: delete override required on prototype required or not?
    // delete Leaflet.Icon.Default.prototype._getIconUrl;
    
    // sets default icon path for leaflet icons/markers
    Leaflet.Icon.Default.mergeOptions({
      iconRetinaUrl: 'leaflet/images/marker-icon-2x.png',
      iconUrl: 'leaflet/images/marker-icon.png',
      shadowUrl: 'leaflet/images/marker-shadow.png',
    });

    // for checking if map is mounted or not, used in getting current user location
    isMounted.current = true;

    return () => {
      isMounted.current = false;
    };
  }, []);
  ```

2023-05-02 05:09 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> +        if (isMounted.current) {
🔥

2023-05-02 05:11 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> -        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
can we please keep the attribution to be nice to OpenStreetMaps? I think it might be required in the license anyways.

2023-05-02 05:13 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
>        <SetViewOnUserLocation />
Maybe in the future, we can move this out to it's own component

2023-05-02 05:17 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> +        })}
```suggestion
   markers.map((marker) =>  <Marker key={marker.id} position={marker.location} />)}
```
and we can add an `id` to the markers object from the `formSubmit`. Do you know if firestore will allow us to generate our own ids or we should get an id from firestore when we create a new form report? Just thinking ahead

2023-05-02 05:31 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
> +            className="flex items-center bg-primary hover:primary-700 text-white font-bold py-2.5 px-3.5 rounded-xl"
```suggestion
            className="flex items-center bg-primary hover:bg-primary/90 text-background font-bold py-2.5 px-3.5 rounded-xl"
```
FYI: `hover:primary-700` is not a utility class but `hover:bg-primary/90` is. We don't have tailwind configured with numbers on our custom color classes. Not sure what you were trying to accomplish with the hover.

2023-05-02 05:32 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
> +          className="block w-full p-2 text-black border border-gray-300 rounded-lg bg-white focus:ring-primary focus:border-primary shadow-md"
```suggestion
          className="block w-full p-2 text-foreground border border-gray-300 rounded-lg bg-background focus:ring-primary focus:border-primary shadow-md"
```

Not sure about the borders off the top of my head but can you match to the figma spec? It keeps refactoring in the future A LOT easier if we want to update colors and there are only 5-6 of them and not like 40 +.

2023-05-02 05:37 UTC, toreylittlefield commented on packages/client/store/store.js
> +    setGeoData: (location) => set(state => state.geoData = location)
Not sure if this should work as you're mutating the state and that property `geoData` is a object. Be careful of mutating state and objects/arrays. Look at how `shallow` checks are preformed differently for primitives vs objects/arrays in state update check like zustand or just react. 

```suggestion
    setGeoData: (location) => set({geoData: location})
```

2023-05-02 05:37 UTC, toreylittlefield commented on packages/client/styles/globals.css
> +  } */
remove

2023-05-02 05:38 UTC, toreylittlefield commented on packages/client/store/formStore.js
> +  resetForm: () => set(initialState),
use vs code to sort these a-z

2023-05-02 05:38 UTC, toreylittlefield commented on packages/client/store/formStore.js
> +};
use vs code to sort these a-z

2023-05-02 05:42 UTC, toreylittlefield commented on packages/client/lib/components/common/icons/Icon.jsx
> +// export const Icon = () => {
Huh? what happened here? Maybe just create a reusable `<Icon />` component with the common TW classes like `h-6 w-7` and have a prop className or whatever to add or override the classes. Up to you. For the `Xmark` if this is used more than once it's fine as it's own reuseable component use use the `<Icon />` component and compose them together. Or you could have a component `<IconWithButton />` or something if you find you need that?

2023-05-02 05:46 UTC, toreylittlefield commented on packages/client/pages/index.tsx
> +  const { showForm } = useFormStore()
don't destructure

2023-05-02 06:00 UTC, toreylittlefield commented on packages/client/pages/index.tsx
> +        {showForm ? (<ReportForm />) : null}
```suggestion
        {showForm ? <ReportForm /> : <>
          <MapWithNoSSR />
          <BottomNav />
        </>}
```

2023-05-02 06:02 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +import useFormStore from '@/store/formStore';
let's keep the imports consistent or we can have eslint enforce the rules. let's use relative or absolute for everything for now.

2023-05-02 06:03 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +const DynamicUpdateView = dynamic(() => import('./FormViews/UpdateView'), {
does this need to be a dynamic import now?  What's the difference between this and this import in `index.tsx`?
```JS 
const MapWithNoSSR = dynamic(() => import('../lib/components/Map'), {
  ssr: false,
});
```

2023-05-02 06:07 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/NavigationButtons/Submit.jsx
> +      className="flex items-center justify-center bg-positive text-white text-xl border py-1.5 m-1 w-1/2 rounded-2xl"
for any `white` use `background` class for any `black` use `foreground` etc... Can you double check these throughout the PR? I've noticed this in a few spots now for the TW classes. Have a look at `global.css` and `tailwind.config.js`. They should match the figma design and I tried to use those names postive, negative, foreground, background etc... in figma too. If there's any questions please let me know. I understand it's confusing.

2023-05-02 06:07 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/NavigationButtons/GoBack.jsx
> +      className="flex items-center justify-center bg-white text-black text-xl border py-1.5 m-1 w-1/2 rounded-2xl"
`black` --> `foreground`, `white` --> `background`

2023-05-02 06:10 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/NavigationButtons/Continue.jsx
> +const Continue = ({ nextStep }) => {
If components like `Continue` or `ExitForm`, `CancelButton` are not reused we can simplify for now an just not make them their own components. We can always refactor in the future, but it's a little complicated right now to break these down if they're not being reused. Can you clean these up where needed?

2023-05-03 02:23 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/FormViews/PhotoView.jsx
> +    // TODO add logic here to check for files type, size, and existing photos to be able to append photos instead of overwriting
has this `TODO` for appending instead of overwriting been implemented? If so can we update the `TODO`?

2023-05-03 02:25 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/FormViews/PhotoView.jsx
> +    }
is this conditional and logic necessary? Won't the `photos.filter()` produce an empty array?

2023-05-05 10:57 UTC, ranegray commented on packages/client/lib/components/BottomNav/BottomNav.jsx
>        <div></div>
@toreylittlefield without the div and with relative positioning its a little off to the right now. i'll give a try to fix it up. this will probably resolve the safari bug too.

2023-05-08 05:39 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +    <div className="bg-white">
```suggestion
    <div className="bg-background">
```

2023-05-08 05:47 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +        {step === 5 ? null : <FormButtons />}
I think this could be refactored into a `map` or `array` to render correct component(s) based on the step. What do you think about that to clean this up and make it more readable? 

Also some logic is just slightly more difficult to read. 
Example 
```JS
        {step === 5 ? <DynamicUpdateView /> : null}

        {step === 5 ? null : <FormButtons />}
 ```
 
 Could just be one ternary instead of two separate ternaries

2023-05-08 06:19 UTC, toreylittlefield commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +        {step === 5 ? null : <FormButtons />}
Not sure if this is correct but maybe something like this to make the code a little more readable and easier to maintain? What do you think @ranegray ?

```JS
import dynamic from 'next/dynamic';
import CategoryView from './FormViews/CategoryView';
import LocationView from './FormViews/LocationView';
import PhotoView from './FormViews/PhotoView';
import SummaryView from './FormViews/SummaryView';
import TitleView from './FormViews/TitleView';
import FormButtons from './NavigationButtons/FormButtons';

import useFormStore from '@/store/formStore';

const DynamicUpdateView = dynamic(() => import('./FormViews/UpdateView'), {
  ssr: false,
});

const renderStepMap = {
  0: CategoryView,
  1: PhotoView,
  2: TitleView,
  3: LocationView,
  4: SummaryView,
  5: DynamicUpdateView,
};

const ReportForm = () => {
  const step = useFormStore((state) => state.step);

  if (!renderStepMap[step]) {
    return null;
  }

  const RenderViewFromStep = renderStepMap[step];

  const isStepFive = step === 5;

  return (
    <div className="bg-white">
      <form
        noValidate
        className={`flex flex-col h-screen overflow-hidden ${
          isStepFive ? '' : 'p-2'
        }`}
      >
        {!isStepFive && (
          <h1 className="text-2xl font-medium">Report your incident</h1>
        )}
        <RenderViewFromStep />

        {!isStepFive && <FormButtons />}
      </form>
    </div>
  );
};

export default ReportForm;
```

2023-05-08 06:21 UTC, toreylittlefield requested changes
I tried to be thorough. Hope the feedback is helpful. Excellent work. After we get this branch in we are really shaping up to have an app where we can read and write from the firestore!
🔥 🔥

2023-05-08 06:21 UTC, toreylittlefield requested changes
I tried to be thorough. Hope the feedback is helpful. Excellent work. After we get this branch in we are really shaping up to have an app where we can read and write from the firestore!
🔥 🔥

2023-05-24 05:23 UTC, toreylittlefield commented
@ranegray I'd like to cut off this branch and then move the existing comments to new issues for later refactoring if that's cool with you. 

Do you have anything else to commit? If you have time can you click the "resolved" button and/or leave any comments on the PR feedback for things you have already fixed up?

This way we can get your changes merged in and then work on refactoring/fixes later in separate issues. Thanks!

2023-05-26 11:31 UTC, ranegray commented on packages/client/lib/components/Map.jsx
> +        })}
Firestore can auto generate ids for us.

2023-05-26 11:43 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
>        <SetViewOnUserLocation />
yeah I guess so but we can refactor later thanks!

2023-05-26 11:46 UTC, ranegray commented on packages/client/lib/components/Map.jsx
> +        })}
I refactored the code for now to generate an id for each marker to use Date.now() for now. We can refactor later if we want.

2023-05-26 11:54 UTC, ranegray commented on packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
> +          className="block w-full p-2 text-black border border-gray-300 rounded-lg bg-white focus:ring-primary focus:border-primary shadow-md"
This will have to be a work in progress. I changed all the white and black to foreground and background but I'll open a new issue to refactor all this.

2023-05-26 11:57 UTC, ranegray commented on packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
> +            className="flex items-center bg-primary hover:primary-700 text-white font-bold py-2.5 px-3.5 rounded-xl"
Imma just remove it. Not sure what I was doing either.

2023-05-26 12:05 UTC, ranegray commented on packages/client/store/formStore.js
> +  resetForm: () => set(initialState),
I did it. But why?

2023-05-26 12:06 UTC, ranegray commented on packages/client/lib/components/common/icons/Icon.jsx
> +// export const Icon = () => {
I want to break this out to separate issue.

2023-05-26 12:48 UTC, ranegray commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +const DynamicUpdateView = dynamic(() => import('./FormViews/UpdateView'), {
They are different maps technically. So I do believe that one is necessary.

2023-05-26 12:50 UTC, ranegray commented on packages/client/lib/components/ReportForm/NavigationButtons/Submit.jsx
> +      className="flex items-center justify-center bg-positive text-white text-xl border py-1.5 m-1 w-1/2 rounded-2xl"
Going to open a new issue for this. I did change all white and blacks but we gotta go through and do borders and stuff slightly differently.

2023-05-26 12:56 UTC, ranegray commented on packages/client/lib/components/ReportForm/FormViews/PhotoView.jsx
> +    }
you're so smart!

2023-05-26 13:00 UTC, ranegray commented on packages/client/lib/components/ReportForm/ReportForm.jsx
> +        {step === 5 ? null : <FormButtons />}
real cleeeeeeeaaaaaaaaannnnnnnn!

2023-05-26 17:36 UTC, toreylittlefield commented on packages/client/store/formStore.js
> +  resetForm: () => set(initialState),
It's shinier 😅

2023-05-27 14:55 UTC, toreylittlefield approved these changes
@ranegray excellent work on this man. It was a big ticket and you did good. Thanks for creating issues as well that's much appreciated!

2023-05-27 14:56 UTC, merged