Ob/issue #17  search bar
TeamPetPoison/pet-poison-alert pull request #38
Opened 2023-04-10 05:48 UTC by Netdreion

i am not sure! if its satisfying  the figma file description , pls let me know if anything need to be changed or approved , thanks in advance

2023-04-10 20:37 UTC, ranegray reviewed
Shoot, looks good to me! Checked out to your branch worked good on my machine. Do we want the map to navigate when we pick a location from the menu or we will implement that later?

2023-04-10 21:17 UTC, Netdreion commented
Hey rane , thanks for the review and yes I believe we would go through that faze, when we start using api to fetch data.

2023-04-13 04:38 UTC, toreylittlefield commented on packages/client/lib/components/Map.jsx
> +import SearchBar from "./SearchBar"
remove the unused import

2023-04-13 04:42 UTC, toreylittlefield commented on package.json
> +  }
Any reason why are you using chakra? That's a React UI component library and we aren't using one in this project. 

Please remove/uninstall the package 
see https://docs.npmjs.com/cli/v9/commands/npm-uninstall?v=true

2023-04-13 04:43 UTC, toreylittlefield commented on tsconfig.base.json
> +    "noImplicitAny": false,
I think I accidentally did this. Can you please can it back to `true`? Thanks

2023-04-13 04:44 UTC, toreylittlefield commented on packages/client/styles/globals.css
> +}
I don't think we need any of these classes now because we're using Tailwind right?

2023-04-13 04:49 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +function SearchBar() {
instead of `SearchBar` as the file and component name how about `LocationSearch` or something? What do you think? It just sounds more specific.

2023-04-13 04:57 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +            placeholder='Type a location'
The placeholder text from the figma spec "Search For Place, Location..."

2023-04-13 04:59 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          <MagnifyingGlassCircleIcon className='w-6 h-6' onClick={() => onSearch(value)} />
Don't show the magnify glass when there is a value, show the XmarkIcon instead. Here you're showing both together. Just show one or the other.

2023-04-13 05:02 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +            <ArrowUturnLeftIcon className='w-6 h-6' onClick={() => setIsOpen(false)} />
let's not use inline arrow functions like this because it's harder to read. Can you move them to a function/handler above like `onChange`, `onSearch` etc...?

2023-04-13 05:02 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +            <Bars3Icon className='w-6 h-6' onClick={() => setIsOpen(true)} />
see comment above about no inline arrow functions.

2023-04-13 05:02 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +            <XMarkIcon className='w-6 h-6' onClick={() => setValue('')} />
see comment above about no inline arrow functions.

2023-04-13 05:06 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +  }
you can actually move this whole function outside/above the component below the mockdata object. It doesn't need to be inside the component (it can be and it won't hurt anything, it just cleans up the readibility of the component). Also by being in the component any function will get recreated everytime the component rerenders just FYI.

2023-04-13 05:15 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          <div className="absolute top-14 left-0 right-0 bg-white border border-solid border-purple-500 rounded-b-lg">
for the colors use the one's defined in the `tailwind.config.js` 

Example instead of `bg-white` we use `bg-background` because if you look at global.css you'll see the CSS variable `--color-background` is a "white" color.

For purple we have `primary` so `border-primary` instead of `border-purple-500`. Although I don't think we want or need any of the purple borders. Maybe these were helpful to you but they're not in the figma spec.

2023-04-13 05:15 UTC, toreylittlefield commented
@Netdreion nice work it looks and works pretty well. I think it's a good attempt.

Feedback on the figma spec is that it could use some further tweaking to get it to match more closely the figma design. If you want I can take care of the rest of that for you if it's annoying right now and you'd like to move on. I think you got the general idea it just requires more precision.

In regards to the functionality, there is one problem/bug I noticed. When you delete the search term the dropdown remains open and shows all the "mock" results right now. Also if you click off / move the focus elsewhere, the search component the dropdown stays open (I think it should close). It looks like you have to click the "back arrow" to close it which is OK but it would be better if clicking out of the search closed the dropdown too.

2023-04-29 10:40 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +function SearchBar() {
done

2023-04-29 10:41 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +  }
ok, its done

2023-04-29 10:42 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +            <ArrowUturnLeftIcon className='w-6 h-6' onClick={() => setIsOpen(false)} />
ok , made functions for each

2023-04-29 10:42 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +            placeholder='Type a location'
ok it replaced

2023-04-29 10:43 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +          <div className="absolute top-14 left-0 right-0 bg-white border border-solid border-purple-500 rounded-b-lg">
changed to white

2023-04-29 10:48 UTC, Netdreion commented on packages/client/lib/components/Map.jsx
> +import SearchBar from "./SearchBar"
removed

2023-04-29 10:49 UTC, Netdreion commented on package.json
> +  }
no reason , i added so many things it got mixed up sorry.

2023-04-29 10:51 UTC, Netdreion commented on package.json
> +  }
removed

2023-04-29 10:53 UTC, Netdreion commented on tsconfig.base.json
> +    "noImplicitAny": false,
its true now

2023-04-29 10:54 UTC, Netdreion commented on packages/client/styles/globals.css
> +}
fixed

2023-04-29 11:01 UTC, Netdreion commented
i tried to fix and change issues with the suggestions given

2023-05-03 05:34 UTC, toreylittlefield requested changes
Nice work 💯 asked for some changes please and then we'll get this merged in.

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +                className="px-5 py-2 hover:bg-purple-200 cursor-pointer"
```suggestion
                className="px-5 py-2 hover:bg-selected/20 cursor-pointer"
```
Or maybe `hover:bg-selected/10`. This way we don't have to manage yet another color.

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +              <div
I am thinking this could be a `<ul />` as a parent with each item as a `<li />` and instead of a `<div />` just use a `<button />`.

Each element has more "semantic" meaning than just a `<div />` and is good for accessibility as well (important). Also a <button /> automatically handles "tabbing" and will register the `Enter` key as a `onClick` which is good. A `<div />` cannot do any of these things automatically.

@Netdreion @ranegray 
See https://www.youtube.com/watch?v=pMoL2URoqhI

Something like:

```JS
<ul className="absolute top-14 left-0 right-0 bg-white border border-solid border-white-500 rounded-b-lg">
  {results.slice(0, 10).map((item) => (
    <li
      key={item.name}
      className="px-5 py-2 hover:bg-selected/20 cursor-pointer"
    >
      <button
        onClick={() => {
          setValue(item.name);
          handleSearch();
        }}
      >
        {item.name}
      </button>
    </li>
  ))}
</ul>
```

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +    setValue(value);
Just an opinion: if the user types a location and then clears the input the dropdown list should not appear. @ranegray @Netdreion what do you think?

Can you implement that change?

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          <div className="absolute top-14 left-0 right-0 bg-white border border-solid border-white-500 rounded-b-lg">
If you click outside of the list it should hide the list. Here's one such example of implementing a "useOnClickOutside" hook. There are other way's to do this and you don't have to create a React custom hook to do this you could just implement it in this file and we can always refactor into a custom hook later if we need to reuse it.

https://usehooks.com/useOnClickOutside/
or https://www.30secondsofcode.org/react/s/use-click-outside/
or https://www.youtube.com/watch?v=XEQ9nEHYIbw&t=27s

Let me know if I can help!

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +
```suggestion
<button  onClick={handleToggleSearch}>
          {isOpen ? (
            <ArrowUturnLeftIcon className='w-6 h-6' />
          ) : (
            <Bars3Icon className='w-6 h-6' />
          )}
</button>
```

A `<button />` is your friend and you're cursor will change when it's hovered over the button amongst other important things 👍 Generally if you have an `onClick` it's going to be a <button /> unless you know why you're not use a button

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          />
Again, a button is your friend, wrap in a `<button />` and use the `onClick` event handler on the button not the icon `svg`

2023-05-03 05:34 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +            <XMarkIcon className='w-6 h-6' onClick={handleClearInput} />
Again, a button is your friend, wrap in a <button /> and use the onClick event handler on the button not the icon svg

2023-05-03 05:40 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          <div className="absolute top-14 left-0 right-0 bg-white border border-solid border-purple-500 rounded-b-lg">
@Netdreion don't use `white` use `bg-background`
`background` is white
`foreground` is black

See these CSS vars we setup which is in `global.css`
![image](https://user-images.githubusercontent.com/52614742/235839271-7d269c4c-9dc4-43bb-a3b8-e323ea3aa48b.png)

In the `tailwind.config.css` where we turn the CSS vars in TW utility classes like `primary`, `foreground`, `background` etc...
So that's how we get the `bg-background` or `text-foreground` or `bg-primary`. These custom colors we've configured with tailwind so just use these. The figma should match these color names i hope.

![image](https://user-images.githubusercontent.com/52614742/235839745-9f26a84e-e5e8-450b-b997-66053853b8e8.png)

2023-05-03 05:42 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +          <div className="absolute top-14 left-0 right-0 bg-white border border-solid border-purple-500 rounded-b-lg">
Try to update any color that is not from our custom color utility classes to use the custom color utility classes. Check border, bg, text etc...

2023-05-03 05:48 UTC, toreylittlefield commented
Just FYI I clicked `Resolve conversation` button just today on all the previous things you've fixed so they're not showing, but you can still click to see the old comments. Nice work man 👍

2023-05-04 03:22 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +    setValue(value);
i think that will work

2023-05-04 03:31 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +
got it!

2023-05-04 04:06 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +            <XMarkIcon className='w-6 h-6' onClick={handleClearInput} />
done!

2023-05-04 04:24 UTC, Netdreion commented on packages/client/lib/components/SearchBar.jsx
> +                  handleSearch();
ok added in a single function

2023-05-08 04:16 UTC, toreylittlefield commented
FYI I just removed the `node_modules` directory from `packages/client` to fix that issue and installed `@heroicons/react` in the `packages/client` workspace since this is a monorepo. Nothing you need to do just wanted to make you aware of the changes. 

I also took the opportunity to just move some of the `dependencies` to the correct `package.json` now that we're using a monorepo.

2023-05-08 04:54 UTC, toreylittlefield commented
Looks like there's an extra border or something
![image](https://user-images.githubusercontent.com/52614742/236737039-e9556dff-5575-4a7d-9988-3ba198c6cddc.png)

2023-05-08 04:57 UTC, toreylittlefield commented
Looks like the "X" close icon is showing by default instead of other search icon with magnifying glass (see the figma spec). Furthermore, I think clicking on the magnifying glass icon should focus on the search input so the user can start typing. This is a typical behavior in most search bars.
![image](https://user-images.githubusercontent.com/52614742/236737286-8a54d2c9-7973-45b8-9bdf-be7532d2451d.png)

2023-05-08 04:59 UTC, toreylittlefield commented
When typing in the search both the "X" and "magnifying glass" icons appear together. It should be only an "X" which should clear the search.
![image](https://user-images.githubusercontent.com/52614742/236737616-658b6546-f534-4dc1-b0ae-a1fe3f730e94.png)

2023-05-08 05:04 UTC, toreylittlefield commented
When you first load the page there's a thin empty element that later looks like it disappears? Not totally sure if it comes back but it shouldn't be there to start. I am guessing this is the "search results" and it's some small bug. I drew orange arrows in the pic below because it's hard to see.

![image](https://user-images.githubusercontent.com/52614742/236738296-056e33fb-b4c4-478f-94be-3a460a444b77.png)

2023-05-08 05:06 UTC, toreylittlefield commented
Clicking on a search result item should update the search result `input` to be the same "text" as the search result `item`. Currently it does nothing except close the search result dropdown.

![image](https://user-images.githubusercontent.com/52614742/236738585-545a1e4d-b2d2-42c6-87d5-392e86dc81c9.png)

2023-05-08 05:10 UTC, toreylittlefield commented
If there are no search result the hamburger "3-bars" icon should either be
1. disabled and clicking it does nothing
OR
2. clicking it shows the current search results and if there are 0 results, then the search results can display _"0 search results found for "search term"_ or something like that which is typical behavior in most search bars.

Currently, if you click the "3-bars" you get the back arrow but no search results. This doesn't make sense unless you implement the 2nd option above. Otherwise, do option 1 if you prefer. Up to you.
![image](https://user-images.githubusercontent.com/52614742/236739067-aab6c6bb-632c-4105-a4cc-1704cc7e8271.png)

2023-05-08 05:20 UTC, toreylittlefield commented
Another issue. Here's the steps to reproduce.

Reproduce:
1. type "a" in the search. The results should be 4.
2. click somewhere outside or close the search results to move the `focus` off the `input`.
3. the input field should still only have "a" as an `input` but when `focusing` again on the input, the search results do not appear again until you start typing more characters into the input field. 

Can we always display the search results if the `input` field has the `focus`?

2023-05-08 05:23 UTC, toreylittlefield commented on packages/client/lib/components/SearchBar.jsx
> +
@Netdreion nice work. Can you move the file `useOnClickOutside.js` inside a new directory `lib/hooks/` and just move it into `hooks` folder? This is the typical folder structure you see for custom hooks. Then the `lib` folder will have `components`, `firebase`, and `hooks` FYI.

2023-05-08 05:27 UTC, toreylittlefield commented
@Netdreion just a general comment. Do you have `prettier` installed on your vs code? It looks like your code is not formatted. Prettier should automatically format your code whenever you hit save. If not, then turn that setting on. 

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2023-05-08 05:29 UTC, toreylittlefield requested changes
A few more issues to resolve but making great progress almost done. Nice work @Netdreion 🚀

2023-05-18 11:49 UTC, Netdreion commented
> When typing in the search both the "X" and "magnifying glass" icons appear together. It should be only an "X" which should clear the search. ![image](https://user-images.githubusercontent.com/52614742/236737616-658b6546-f534-4dc1-b0ae-a1fe3f730e94.png)

fixed it , turn (false) to (true)

2023-05-19 16:19 UTC, Netdreion commented
> Looks like the "X" close icon is showing by default instead of other search icon with magnifying glass (see the figma spec). Furthermore, I think clicking on the magnifying glass icon should focus on the search input so the user can start typing. This is a typical behavior in most search bars. ![image](https://user-images.githubusercontent.com/52614742/236737286-8a54d2c9-7973-45b8-9bdf-be7532d2451d.png)

ok finally fix it

2023-05-19 16:44 UTC, Netdreion commented
> When typing in the search both the "X" and "magnifying glass" icons appear together. It should be only an "X" which should clear the search. ![image](https://user-images.githubusercontent.com/52614742/236737616-658b6546-f534-4dc1-b0ae-a1fe3f730e94.png)

it fixed

2023-05-20 11:05 UTC, Netdreion commented
> Clicking on a search result item should update the search result `input` to be the same "text" as the search result `item`. Currently it does nothing except close the search result dropdown.
> 
> ![image](https://user-images.githubusercontent.com/52614742/236738585-545a1e4d-b2d2-42c6-87d5-392e86dc81c9.pn



function handleListItemClick(name) {
    setValue(name);
    setIsOpen(false);    this is the function 

<li
                  key={item.name}
                  className="px-5 py-2 hover:bg-selected-10 cursor-pointer"
                  onClick={() => handleListItemClick(item.name)}
                >
                  {item.name}
                </li>

i dont know why when clicked the value not reflecting on the input field ?

2023-05-20 11:11 UTC, toreylittlefield commented
@Netdreion can you provide the code snippet again or the screenshot? I can't really see either.

2023-05-24 05:21 UTC, toreylittlefield commented
@ranegray I'd like to cut off this branch and then move the existing comments to new issues for later refactoring if that's cool with you. 

Do you have anything else to commit? If you have time can you click the "resolved" button and/or leave any comments on the PR feedback for things you have already fixed up?

This way we can get your changes merged in and then work on refactoring/fixes later in separate issues. Thanks!

2023-05-25 10:08 UTC, Netdreion commented
> @Netdreion is this branch ready for re-review or are there additional changes you're still working on? Thanks!
> 
> If you have time can you click the "resolved" button and/or leave any comments on the PR feedback for things you have already fixed up? That way we can cleanup some of the comments on this branch to make it easier to read. 🙇‍♂️

yes its for re-review unfortunately  it does not satisfy all the suggested requirements but i tried my best , i hope it will be enough to do the job , i will go back and improve it , when i have better understanding and enough skills to get things what it suppose to be . I am having hard time  follow and coup with it when code get bigger , thank you for keeping up with me:)

2023-05-25 10:20 UTC, toreylittlefield commented
For sure good work! I'll take a look at it and we can get it merged in. We can always refactor or make changes later.

2023-05-27 14:25 UTC, toreylittlefield approved these changes
@Netdreion nice work man it's looking pretty good. Let's merge it :shipit: . Thanks for all the effort on this!

2023-05-27 14:26 UTC, toreylittlefield commented
> > Clicking on a search result item should update the search result `input` to be the same "text" as the search result `item`. Currently it does nothing except close the search result dropdown.
> > ![image](https://user-images.githubusercontent.com/52614742/236738585-545a1e4d-b2d2-42c6-87d5-392e86dc81c9.pn
> 
> ```js
> function handleListItemClick(name) {
>   setValue(name);
>   setIsOpen(false);
> }
> 
> <li
>   key={item.name}
>   className="px-5 py-2 hover:bg-selected-10 cursor-pointer"
>   onClick={() => handleListItemClick(item.name)}
> >
>   {item.name}
> </li>;
> ```
> 
> i dont know why when clicked the value not reflecting on the input field ?

@Netdreion just leaving a comment that we looked at this one together and fixed the issue 👍

2023-05-27 14:26 UTC, merged